version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/clientapp/android"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"

