name: Build TgBot++ (macOS)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up dependencies
        run: |
          brew install boost ninja llvm@17 lld webp libpng libgit2 googletest jsoncpp openssl fmt
          git submodule update --init

      - name: Compile with HomeBrew Clang
        env: 
          CC: /opt/homebrew/opt/llvm/bin/clang
          CXX: /opt/homebrew/opt/llvm/bin/clang++
        run: |
          mkdir build
          cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=ON .
          cmake --build build -j4

      - name: Run Tests
        run: |
            cd build
            ctest --output-on-failure --timeout 30
  
