name: Build TgBot++ (macOS)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

        # https://github.com/Homebrew/homebrew-core/issues/169820#issuecomment-2080459578
      - name: Set up dependencies
        run: |
          brew install boost ninja gcc webp libpng libgit2 googletest jsoncpp openssl fmt
          git submodule update --init

      - name: Compile with Apple GCC
        env: 
          CC: gcc
          CXX: g++
        run: |
          mkdir build
          cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Debug .
          cmake --build build -j4

      - name: Run Tests
        env: 
          DATABASE_BACKEND: sqlite:new.db
        run: |
            ./build/bin/TgBot++_DatabaseCtl set_owner_id 12345
            ./build/bin/TgBot++_test
  
