name: Build TgBot++ (macOS)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Set up dependencies
        run: |
          brew install boost protobuf ninja llvm
          git submodule update --init

      - name: Compile with Apple Clang
        env: 
          CC: /usr/local/opt/llvm/bin/clang
          CXX: /usr/local/opt/llvm/bin/clang++
          LDFLAGS: "-L/usr/local/opt/protobuf/lib -L/usr/local/opt/abseil/lib"
        run: |
          mkdir build
          cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release .
          cmake --build build

      - name: Run Tests
        run: |
            cd build
            ./TgBot++_test
  