name: Build TgBot++ (macOS)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

        # https://github.com/Homebrew/homebrew-core/issues/169820#issuecomment-2080459578
      - name: Set up dependencies
        run: |
          brew install boost ninja llvm
          git submodule update --init
          sed -i '' '/^#define _LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS/d' "$(brew --prefix llvm)"/include/c++/v1/__config_site

      - name: Compile with Apple Clang
        env: 
          CC: /opt/homebrew/opt/llvm/bin/clang
          CXX: /opt/homebrew/opt/llvm/bin/clang++
          LDFLAGS: "-L/opt/homebrew/opt/protobuf/lib -L/opt/homebrew/opt/abseil/lib"
        run: |
          mkdir build
          cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release .
          cmake --build build -j4

      - name: Run Tests
        run: |
            cd build
            ./bin/TgBot++_test
  
