name: Build TgBot++ Client (Windows)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg integrate install
        .\vcpkg\vcpkg install zlib abseil openssl boost

    - name: Build solution
      run: |
        cd clientapp/windows/TgBotClient
        msbuild TgBotClient.sln /p:Configuration=Release
