name: Build TgBot++ (Windows MSVC)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
           arch: x64
           
      - name: Checkout submodules
        run: |
          git submodule update --init

      - name: Install packages
        run: |
          git clone https://github.com/microsoft/vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg integrate install
          .\vcpkg\vcpkg install curl boost

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build all targets
        run: |
          cmake --build . -j4
